api/docs/player-api.yml, api/tests/src/player_api_tests.js, server/src/player_api.hpp, server/src/player_api_json.cpp, server/src/player_api_json.hpp, server/src/player_deadbeef/player.hpp, server/src/player_deadbeef/player_control.cpp, server/src/player_deadbeef/player_misc.cpp, server/src/player_foobar2000/player.hpp, server/src/player_foobar2000/player_control.cpp, webui/src/player_model.js, webui/src/window_controller.js
Implement player identification (name, version, etc)
Fixes #53
=> Player identification

api/client/api_client.js, api/docs/player-api.yml, api/tests/src/artwork_tests.js, server/src/artwork_controller.cpp, server/src/artwork_controller.hpp, server/src/player_api.hpp, server/src/player_deadbeef/artwork_request.cpp, server/src/player_deadbeef/artwork_request.hpp, server/src/player_deadbeef/player.hpp, server/src/player_deadbeef/player_misc.cpp, server/src/player_deadbeef/utils.cpp, server/src/player_deadbeef/utils.hpp, server/src/server_host.cpp
=> Artwork redesign

webui/src/app.js, webui/src/app_model.js, webui/src/file_browser.js, webui/src/file_browser_header.js, webui/src/index.html, webui/src/index.js, webui/src/notification_group.js, webui/src/notification_model.js, webui/src/playback_control.js, webui/src/style.less, webui/src/timer.js
=> Implement item addition notifications

webui/src/file_browser_header.js, webui/src/file_browser_model.js, webui/src/style.less, webui/src/utils.js
=> File browser breadcrumbs

js/webui/src/app.js, js/webui/src/app_model.js, js/webui/src/data_table.js, js/webui/src/dom_utils.js, js/webui/src/file_browser.js, js/webui/src/index.js, js/webui/src/media_size_controller.js, js/webui/src/playback_control.js, js/webui/src/playlist_content.js, js/webui/src/scroll_manager.js, js/webui/src/style.less, js/webui/src/urls.js
=> Add button to locate current track

docs/change-log.md, js/api_tests/src/query_api_tests.js, server/src/foobar2000/utils.cpp
=> Volume events fix

docs/change-log.md, js/api_tests/src/deadbeef/test_context.js, js/api_tests/src/foobar2000/test_context.js, js/api_tests/src/player_api_tests.js, js/api_tests/src/request_handler.js, js/client/src/index.js, js/client/src/utils.js, js/webui/src/request_handler.js, server/src/parsing.hpp, server/src/tests/CMakeLists.txt, server/src/tests/parsing_tests.cpp
=> Implement proper escaping for array query string parameters

docs/change-log.md, docs/player-api.yml, js/api_tests/src/player_api_tests.js, js/client/src/player_client.js, js/webui/src/playback_control.js, js/webui/src/player_model.js, server/src/deadbeef/player.hpp, server/src/deadbeef/player_control.cpp, server/src/deadbeef/player_misc.cpp, server/src/deadbeef/utils.cpp, server/src/deadbeef/utils.hpp, server/src/foobar2000/player.hpp, server/src/foobar2000/player_control.cpp, server/src/player_api.hpp, server/src/player_controller.cpp
=> Implement next/previous by expression operations

js/webui/src/data_table.js, js/webui/src/file_browser.js, js/webui/src/file_browser_header.js, js/webui/src/general_settings.js, js/webui/src/playlist_content.js, js/webui/src/playlist_menu.js, js/webui/src/playlist_model.js, js/webui/src/settings_model.js, js/webui/src/style.less
=> Advanced "Add" operations

docs/change-log.md, js/webui/src/general_settings.js, js/webui/src/model_binding.js, js/webui/src/setting_editor.js, js/webui/src/settings_model.js, js/webui/src/style.less
=> Dark theme & UI tweaks

js/webui/src/css_settings_controller.js, js/webui/src/general_settings.js, js/webui/src/index.js, js/webui/src/media_theme_controller.js, js/webui/src/settings_model.js
=> webui: allow to use system ui theme

js/webui/src/control_bar.js, js/webui/src/player_features.js, js/webui/src/player_model.js, js/webui/src/volume_control.js
=> webui: always use linear <-> db transformations for db volume type

cpp/server/controller.hpp, cpp/server/deadbeef/CMakeLists.txt, cpp/server/deadbeef/player.hpp, cpp/server/deadbeef/player_control.cpp, cpp/server/deadbeef/player_misc.cpp, cpp/server/deadbeef/player_options.cpp, cpp/server/deadbeef/player_options.hpp, cpp/server/foobar2000/CMakeLists.txt, cpp/server/foobar2000/player.hpp, cpp/server/foobar2000/player_control.cpp, cpp/server/foobar2000/player_misc.cpp, cpp/server/foobar2000/player_options.cpp, cpp/server/foobar2000/player_options.hpp, cpp/server/player_api.hpp, cpp/server/player_api_json.cpp, cpp/server/player_api_json.hpp, cpp/server/player_controller.cpp, cpp/server/player_controller.hpp, cpp/server/request.hpp, docs/player-api.yml, js/api_tests/src/player_api_tests.js, js/api_tests/src/test_player_client.js, js/client/src/player_client.js, js/webui/src/control_bar.js, js/webui/src/playback_control.js, js/webui/src/player_model.js
=> Add player options plumbing, add stop-after-current option

docs/player-api.yml
=>  Migrate API docs to OpenAPI 3

scripts/build.sh
A small change that may save a lot of time :)
=> Use max number of cores for deadbeef build

docs/change-log.md, js/webui/src/index.js, js/webui/src/style.less
- Prevent default overscroll behavior (e.g. reload page)
- Adjust UI height to avoid being hidden by the browser controls
=> Improve UI layout for mobile browsers

js/webui/src/app.js, js/webui/src/columns_settings.js, js/webui/src/columns_settings_menu.js, js/webui/src/control_bar.js, js/webui/src/file_browser.js, js/webui/src/file_browser_header.js, js/webui/src/general_settings.js, js/webui/src/model_binding.js, js/webui/src/playback_control.js, js/webui/src/playback_info_bar.js, js/webui/src/playlist_content.js, js/webui/src/playlist_menu.js, js/webui/src/playlist_switcher.js, js/webui/src/position_control.js, js/webui/src/setting_editor.js, js/webui/src/settings_content.js, js/webui/src/settings_header.js, js/webui/src/status_bar.js, js/webui/src/view_switcher.js, js/webui/src/volume_control.js
=> webui: use context to pass models 

docs/change-log.md, js/webui/CMakeLists.txt, js/webui/src/app_model.js, js/webui/src/data_source.js, js/webui/src/data_table.js, js/webui/src/play_queue_model.js, js/webui/src/player_features.js, js/webui/src/playlist_content.js, js/webui/src/style.less
=> add playback queue support in web UI

cpp/server/deadbeef/player.hpp, cpp/server/deadbeef/player_control.cpp, cpp/server/foobar2000/player.hpp, cpp/server/foobar2000/player_control.cpp, cpp/server/foobar2000/player_misc.cpp, cpp/server/player_api.hpp, cpp/server/player_api_json.cpp, cpp/server/player_controller.cpp, docs/player-api.yml, js/api_tests/src/player_api_tests.js, js/client/src/player_client.js, js/webui/src/about_box.js, js/webui/src/player_model.js, js/webui/src/style.less, js/webui/src/volume_control.js
=> Introduce upDown volume type

ChangeLog.md, cpp/server/deadbeef/player.hpp, cpp/server/deadbeef/player_control.cpp, cpp/server/foobar2000/player.hpp, cpp/server/foobar2000/player_control.cpp, cpp/server/player_api.hpp, cpp/server/player_controller.cpp, cpp/server/player_controller.hpp, docs/player-api.yml, js/api_tests/src/player_api_tests.js, js/client/src/player_client.js, js/webui/src/general_settings.js, js/webui/src/playback_control.js, js/webui/src/player_model.js, js/webui/src/settings_model.js
=> add ability to combine Play and Pause buttons
